version: '3.9'

services:

  events-based-store:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    container_name: events-based-store
    ports:
      - 3000:3000
    networks:
      events-based-store:
        ipv4_address: "172.20.200.3"
networks:
  events-based-store:
    ipam:
      driver: default
      config:
        - subnet: "172.20.201.0/24"
